version: '2'

services:

  mysql:
    container_name: database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_bin
    restart: always
    privileged: true
    environment:
      - "MYSQL_ROOT_PASSWORD=Test"
      - "MYSQL_HOST=0.0.0.0"
      - "MYSQL_USER=crud"
      - "MYSQL_DATABASE=examedb"
      - "MYSQL_PASSWORD=Test"
      - "MYSQL_PORT=3306"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "TZ=America/Sao_Paulo"
    cap_add:
      - SYS_NICE
    networks:
      - "networks-php-general"

  server:
    build: .
    container_name: applications
    privileged: true
    restart: always  
    ports:
      - "20022:22"
      - "20080:80"
      - "20443:443"
      - "4000:3000"
    volumes:
      - "./backend:/var/www/html"
      - "./front:/var/www/frontend"
    networks:
      - "networks-php-general"

networks:
  networks-php-general:
    driver: "bridge"
